CREATE TABLE USERS(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRSTNAME VARCHAR(100) NOT NULL,
  LASTNAME VARCHAR(100) NOT NULL,
  USERNAME VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD TEXT NOT NULL,
  LANGPREF VARCHAR(100) NOT NULL
);

CREATE TABLE CODE(
  CODE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  LANG VARCHAR(100),
  CODEBODY TEXT,
  CODELINK TEXT,
  CODETITLE TEXT NOT NULL,
  CODETOPIC VARCHAR(100),
  CODEDESC TEXT,
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE AUTH_USER_GROUP (
  AUTH_USER_GROUP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(128) NOT NULL,
  AUTH_GROUP VARCHAR(128) NOT NULL,
  CONSTRAINT USER_AUTH_USER_GROUP_FK FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME),
  UNIQUE (USERNAME, AUTH_GROUP)
)
