CREATE TABLE USERS(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRSTNAME VARCHAR(100) NOT NULL,
  LASTNAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL UNIQUE,
  PASSWORD VARCHAR(100) NOT NULL,
  LANGPREF VARCHAR(100) NOT NULL
);

CREATE TABLE CODE(
  CODE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  LANG VARCHAR(100),
  CODEBODY TEXT,
  CODELINK TEXT,
  CODETITLE TEXT NOT NULL,
  CODETOPIC VARCHAR(100),
  CODEDESC TEXT,
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);